apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: examples
  annotations:
    github.com/project-slug: arboleda-alejandro/examples
    backstage.io/techdocs-ref: dir:.
spec:
  type: other
  lifecycle: experimental
  owner: user:default/arboleda-alejandro

